### ISSUE TITLE
支付宝记步

### ISSUE THREAD

**Issue by rickychaw** [YiuChoi/SportEditor#5]
支付宝只有第一天可以用，后面完全没反应一步也没有了。是什么原因啊？望解答修复

**Comment by trysh** [comment]
还有，支付宝最高支持到什么版本可否告知一下。我用1.29版，支付宝9.9.3版，无效

**Comment by YiuChoi** [comment]
支付宝目前存在蜜汁bug，安装第一天有效，第二天失效

2016-11-01 10:04 GMT+08:00, trysh notifications@github.com:
